package application;

import java.net.URL;
import java.util.ResourceBundle;

import javafx.fxml.FXML;
import javafx.fxml.Initializable;
import javafx.scene.control.Button;

import javafx.scene.control.TextField;

import javafx.scene.control.Label;

import javafx.scene.input.MouseEvent;

import javafx.scene.control.TableView;

import javafx.scene.control.TableColumn;

public class MainController implements Initializable{
	@FXML
	private Label id;
	@FXML
	private Label firstName;
	@FXML
	private Label lastName;
	@FXML
	private Label email;
	@FXML
	private Label adress;
	@FXML
	private Label city;
	@FXML
	private Label country;
	@FXML
	private TextField conId;
	@FXML
	private TextField conFirstName;
	@FXML
	private TextField conLastName;
	@FXML
	private TextField ConEmail;
	@FXML
	private TextField conAdress;
	@FXML
	private TextField conCity;
	@FXML
	private TextField conCountry;
	@FXML
	private TableView<Candidats> tabCondidats;
	@FXML
	private TableColumn<Candidats, Integer> clmnId;
	@FXML
	private TableColumn<Candidats, String> clmnFirstName;
	@FXML
	private TableColumn<Candidats, String> clmLastName;
	@FXML
	private TableColumn<Candidats, String> clmnEmail;
	@FXML
	private TableColumn<Candidats, String> ClmnAdress;
	@FXML
	private TableColumn<Candidats, String> ClmnCity;
	@FXML
	private TableColumn<Candidats, String> clmnCountry;
	@FXML
	private Button btnCreate;
	@FXML
	private Button btnUpdate;
	@FXML
	private Button btnDelete;
	@FXML
	private Label welcome;

	// Event Listener on TableView[#tabCondidats].onMouseClicked
	@FXML
	public void handleButtonAction(MouseEvent event) {
		// TODO Autogenerated
	}

	@Override
	public void initialize(URL arg0, ResourceBundle arg1) {
		// TODO Auto-generated method stub
		
	}
}
